XPATH_TAB_EMPLOYEE_LIST_PIM    =   "(//a[@class='oxd-topbar-body-nav-tab-item'])[1]"
XPATH_EMPLOYEE_LIST_TABLE_TXT  =   "//h5[@class='oxd-text oxd-text--h5 oxd-table-filter-title']"
XPATH_TXT_EMPLOYEE_NAME       =   "(//div[@class='oxd-autocomplete-wrapper']//input)[1]"
XPATH_TXT_EMPLOYEE_ID         =   "//div[@class='oxd-input-group__label-wrapper']/following-sibling::*//input[not(@type) and not(@placeholder)]"
XPATH_BTN_SEARCH_OR_SAVE      =   "//button[@type='submit']"
XPATH_TABLE_EMPLOYEE_RECORDS  =   "//div[@class='oxd-table-body']/div[@class='oxd-table-card']"
XPATH_CHECK_BOX_SELECT_ALL    =   "//div[@class='orangehrm-container']//div[@class='oxd-checkbox-wrapper']"
XPATH_BTN_DELETE              =   "//button[contains(@class,'label-danger')]"
XPATH_ICON_CONFIRM_DELETE     =   "//i[@class='oxd-icon bi-trash oxd-button-icon']"